# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# routes = [
# 'Route N5 - South Shore Night Bus',
# 'Route 6 - Jackson Park Express',
# 'Route 7 - Harrison',
# 'Route 8 - Halsted',
# 'Route 8A - South Halsted',
# 'Route 9 - Ashland',
# 'Route 10 - Museum of Science and Industry',
# 'Route 11 - Lincoln',
# 'Route 12 - Roosevelt',
# 'Route J14 - Jeffery Jump',
# 'Route 15 - Jeffery Local',
# 'Route 18 - 16th/18th',
# 'Route 20 - Madison',
# 'Route 21 - Cermak',
# 'Route 22 - Clark',
# 'Route 24 - Wentworth',
# 'Route 26 - South Shore Express',
# 'Route 28 - Stony Island ',
# 'Route 29 - State',
# 'Route 30 - South Chicago',
# 'Route 34 - South Michigan',
# 'Route 35 - 31st/35th',
# 'Route 36 - Broadway',
# 'Route 37 - Sedgwic',
# 'Route 39 - Pershing',
# 'Route 146 - Inner Drive/Michigan Express',
# 'Route 43 - 43rd',
# 'Route 44 - Wallace/Racine',
# 'Route 47 - 47th',
# 'Route 48 - South Damen',
# 'Route 49 - Western',
# 'Route 49B - North Western',
# 'Route 50 - Damen',
# 'Route 51 - 51st',
# 'Route 52 - Kedzie/California',
# 'Route 52A - South Kedzie',
# 'Route 53 - Pulaski',
# 'Route 53A - South Pulaski',
# 'Route 54 - Cicero',
# 'Route 54A - North Cicero/Skokie Blvd.',
# 'Route 54B - South Cicero',
# 'Route 55 - Garfiel',
# 'Route 55A - 55th/Austin',
# 'Route 55N - 55th/Narragansett',
# 'Route 56 - Milwaukee',
# 'Route 57 - Laramie',
# 'Route 59 - 59th/61st',
# 'Route 60 - Blue Island/26th',
# 'Route 62 - Archer',
# 'Route 62H - Archer/Harlem',
# 'Route 63 - 63rd',
# 'Route 63W - West 63rd',
# 'Route 65 - Grand',
# 'Route 66 - Chicago',
# 'Route 67 - 67th/69th/71st',
# 'Route 68 - Northwest Highway',
# 'Route 70 - Division',
# 'Route 71 - 71st/South Shore',
# 'Route 72 - North',
# 'Route 73 - Armitage',
# 'Route 74 - Fullerton',
# 'Route 75 - 74th/75th',
# 'Route 76 - Diversey',
# 'Route 77 - Belmont',
# 'Route 78 - Montrose',
# 'Route 79 - 79th',
# 'Route 80 - Irving Park',
# 'Route 81 - Lawrence',
# 'Route 81W - West Lawrence',
# 'Route 82 - Kimball/Homan',
# 'Route 84 - Peterson',
# 'Route 85 - Central',
# 'Route 85A - North Central',
# 'Route 86 - Narragansett/Ridgeland',
# 'Route 87 - 87th',
# 'Route 88 - Higgins',
# 'Route 90 - Harlem',
# 'Route 91 - Austin',
# 'Route 92 - Foster',
# 'Route 93 - California/Dodge',
# 'Route 94 - South California',
# 'Route 95E - 93rd/95th',
# 'Route 95W - West 95th',
# 'Route 96 - Lunt',
# 'Route 97 - Skokie',
# 'Route X98 - Avon Express',
# 'Route 100 - Jeffery Manor Express',
# 'Route 103 - West 103rd',
# 'Route 106 - East 103rd',
# 'Route 108 - Halsted/95th',
# 'Route 111 - 111th/King Drive',
# 'Route 111A - Pullman Shuttle',
# 'Route 112 - Vincennes/111th',
# 'Route 115 - Pullman/115th',
# 'Route 119 - Michigan/119th',
# 'Route 205 - Chicago/Golf',
# 'Route 120 - Ogilvie/Streeterville Express',
# 'Route 121 - Union/Streeterville Express',
# 'Route 124 - Navy Pier',
# 'Route 125 - Water Tower Express',
# 'Route 126 - Jackson',
# 'Route 130 - Museum Campus',
# 'Route 132 - Goose Island Express',
# 'Route 134 - Stockton/LaSalle Express',
# 'Route 135 - Clarendon/LaSalle Express',
# 'Route 136 - Sheridan/LaSalle Express',
# 'Route 143 - Stockton/Michigan Express',
# 'Route 146 - Inner Drive/Michigan Express',
# 'Route 147 - Outer Drive Express',
# 'Route 148 - Clarendon/Michigan Express',
# 'Route 151 - Sheridan',
# 'Route 152 - Addison',
# 'Route 155 - Devon',
# 'Route 156 - LaSalle',
# 'Route 157 - Streeterville/Taylor',
# 'Route 165 - West 65th',
# 'Route 169 - 69th/UPS Express',
# 'Route 170 - U. of Chicago/Midway',
# 'Route 171 - U. of Chicago/Hyde Park',
# 'Route 172 - U. of Chicago/Kenwood',
# 'Route 192 - U. of Chicago/Hospitals Express',
# 'Route 201 - Central/Ridge',
# 'Route 206 - Evanston Circulator']

# routes.each do |route|
#   Transportation.create([
#   {route: route, type_transport: "bus"}
#   ])
# end


  # Favorite.create([
  # {type_transp: "train", station_id: "41120", user_id: 3}
  # ])
